// Feature-flags emitter: regenerates a read-only, configuration-driven capability from an
// EmissionSpec in the destination's idiom. No persistence, no credentials — the contrast
// with session-auth is deliberate. Everything interpolated is validated first.
import { jsString, routePath } from '../util/safe.js';

const ENV_NAME = /^[A-Z][A-Z0-9_]{0,63}$/;
const FLAG_NAME = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/;

export function emitFeatureFlagsFromSpec(spec) {
  if (spec.kind !== 'feature-flags') throw new Error(`feature-flags emitter cannot emit a ${spec.kind} capability`);
  const configuration = spec.policies.configuration;
  if (!configuration || typeof configuration.defaults !== 'object') throw new Error('feature-flags spec carries no configuration policy');
  const defaults = Object.entries(configuration.defaults);
  if (!defaults.length || !defaults.every(([k, v]) => FLAG_NAME.test(k) && typeof v === 'boolean')) { const err = new Error('unsafe flag defaults'); err.code = 'unsafe-manifest-value'; throw err; }
  const envVar = configuration.envVar ?? null;
  if (envVar !== null && !ENV_NAME.test(envVar)) { const err = new Error('unsafe environment variable name'); err.code = 'unsafe-manifest-value'; throw err; }
  const op = (role) => { const found = spec.operations.find((o) => o.role === role); return found ? { ...found, path: routePath(found.path, `operations.${role}.path`) } : null; };
  const list = op('list'), evaluate = op('evaluate');
  if (!list) throw new Error('feature-flags spec has no list operation');
  const express = spec.profile === 'express-req-res';
  const dir = spec.dir;
  const files = [];
  files.push({ path: `${dir}/flags.js`, contents: `// Feature flags regenerated by GRAFT from the harvested capability's intent.
// Defaults live in code; ${envVar ? `${envVar} (comma-separated names) enables flags at runtime.` : 'no environment override was harvested.'}
export const DEFAULT_FLAGS = Object.freeze({
${defaults.map(([k, v]) => `  ${jsString(k, 'flag.name')}: ${v ? 'true' : 'false'},`).join('\n')}
});

export function enabledFlags(env = process.env) {
  const flags = { ...DEFAULT_FLAGS };
${envVar ? `  const configured = env[${jsString(envVar, 'configuration.envVar')}];
  if (typeof configured === 'string') for (const name of configured.split(',').map((s) => s.trim()).filter(Boolean)) if (Object.hasOwn(flags, name)) flags[name] = true;
` : ''}  return flags;
}

export function isEnabled(name, env = process.env) {
  const flags = enabledFlags(env);
  return Object.hasOwn(flags, name) ? flags[name] : null;
}
` });
  const listPath = jsString(list.path, 'operations.list.path');
  const evalPath = evaluate ? jsString(evaluate.path, 'operations.evaluate.path') : null;
  files.push({ path: `${dir}/routes.js`, contents: express ? `import express from 'express';
import { enabledFlags, isEnabled } from './flags.js';

const parseJsonBody = express.json();

export function ${spec.registration.name}(app) {
  app.get(${listPath}, (req, res) => res.status(200).json({ flags: enabledFlags() }));
${evaluate ? `  app.post(${evalPath}, parseJsonBody, (req, res) => {
    const name = req.body?.name;
    const enabled = typeof name === 'string' ? isEnabled(name) : null;
    if (enabled === null) return res.status(404).json({ error: 'unknown_flag' });
    return res.status(200).json({ name, enabled });
  });
` : ''}}
` : `import { enabledFlags, isEnabled } from './flags.js';

export function ${spec.registration.name}(app) {
  app.get(${listPath}, async () => ({ status: 200, body: { flags: enabledFlags() } }));
${evaluate ? `  app.post(${evalPath}, async (ctx) => {
    const name = ctx.body?.name;
    const enabled = typeof name === 'string' ? isEnabled(name) : null;
    if (enabled === null) return { status: 404, body: { error: 'unknown_flag' } };
    return { status: 200, body: { name, enabled } };
  });
` : ''}}
` });
  return { profile: spec.profile, dir, files, usesSharedStore: false, specId: spec.specId, registration: spec.registration };
}
